Vagrant.configure("2") do |config|
  # Base box definition
  config.vm.box = "ubuntu/trusty64"

  # Define ansible-host1 VM
  config.vm.define "host1" do |host1|
    host1.vm.hostname = "host1"
    host1.vm.network "private_network", ip: "192.168.56.10"
    host1.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    host1.vm.provision "shell", path: "./scripts/host.sh"
  end
  
  config.vm.define "host2" do |host2|
    host2.vm.hostname = "host2"
    host2.vm.network "private_network", ip: "192.168.56.11"
    host2.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    host2.vm.provision "shell", path: "./scripts/host.sh"
  end
  config.vm.define "host3" do |host3|
    host3.vm.hostname = "host3"
    host3.vm.network "private_network", ip: "192.168.56.12"
    host3.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    host3.vm.provision "shell", path: "./scripts/host.sh"
  end
end