---
- name: Install Docker and Docker Compose
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - docker.io
        update_cache: yes
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_ssh_user }}"
        groups: docker
        append: yes